<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $usuarios = [
            ['name' => 'Admin',        'email' => 'admin@sige.com',        'password' => 'Admin@2024',    'perfil' => 'admin',        'pin' => '7409'],
            ['name' => 'Amanda',       'email' => 'amanda@sige.com',       'password' => 'Operador@2024', 'perfil' => 'operador',     'pin' => '8401'],
            ['name' => 'Daniela',      'email' => 'daniela@sige.com',      'password' => 'Operador@2024', 'perfil' => 'operador',     'pin' => '1974'],
            ['name' => 'Visualizador', 'email' => 'visualizador@sige.com', 'password' => 'Visual@2024',   'perfil' => 'visualizador', 'pin' => null],
            ['name' => 'Angel',        'email' => 'angel@sige.com',        'password' => 'Angel@2024',    'perfil' => 'admin',        'pin' => '3256'],
            ['name' => 'Natan',        'email' => 'natan@sige.com',        'password' => 'Natan@2024',    'perfil' => 'admin',        'pin' => '6183'],
            ['name' => 'Miguel',       'email' => 'miguel@sige.com',       'password' => 'Operador@2024', 'perfil' => 'operador',     'pin' => '6935'],
            ['name' => 'usuario1', 'email' => 'usuario1@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1001'],
            ['name' => 'usuario2', 'email' => 'usuario2@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1002'],
            ['name' => 'usuario3', 'email' => 'usuario3@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1003'],
            ['name' => 'usuario4', 'email' => 'usuario4@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1004'],
            ['name' => 'usuario5', 'email' => 'usuario5@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1005'],
            ['name' => 'usuario6', 'email' => 'usuario6@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1006'],
            ['name' => 'usuario7', 'email' => 'usuario7@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1007'],
            ['name' => 'usuario8', 'email' => 'usuario8@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1008'],
            ['name' => 'usuario9', 'email' => 'usuario9@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1009'],
            ['name' => 'usuario10', 'email' => 'usuario10@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1010'],
            ['name' => 'usuario11', 'email' => 'usuario11@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1011'],
            ['name' => 'usuario12', 'email' => 'usuario12@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1012'],
            ['name' => 'usuario13', 'email' => 'usuario13@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1013'],
            ['name' => 'usuario14', 'email' => 'usuario14@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1014'],
            ['name' => 'usuario15', 'email' => 'usuario15@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1015'],
            ['name' => 'usuario16', 'email' => 'usuario16@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1016'],
            ['name' => 'usuario17', 'email' => 'usuario17@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1017'],
            ['name' => 'usuario18', 'email' => 'usuario18@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1018'],
            ['name' => 'usuario19', 'email' => 'usuario19@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1019'],
            ['name' => 'usuario20', 'email' => 'usuario20@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1020'],
            ['name' => 'usuario21', 'email' => 'usuario21@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1021'],
            ['name' => 'usuario22', 'email' => 'usuario22@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1022'],
            ['name' => 'usuario23', 'email' => 'usuario23@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1023'],
            ['name' => 'usuario24', 'email' => 'usuario24@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1024'],
            ['name' => 'usuario25', 'email' => 'usuario25@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1025'],
            ['name' => 'usuario26', 'email' => 'usuario26@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1026'],
            ['name' => 'usuario27', 'email' => 'usuario27@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1027'],
            ['name' => 'usuario28', 'email' => 'usuario28@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1028'],
            ['name' => 'usuario29', 'email' => 'usuario29@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1029'],
            ['name' => 'usuario30', 'email' => 'usuario30@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1030'],
            ['name' => 'usuario31', 'email' => 'usuario31@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1031'],
            ['name' => 'usuario32', 'email' => 'usuario32@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1032'],
            ['name' => 'usuario33', 'email' => 'usuario33@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1033'],
            ['name' => 'usuario34', 'email' => 'usuario34@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1034'],
            ['name' => 'usuario35', 'email' => 'usuario35@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1035'],
            ['name' => 'usuario36', 'email' => 'usuario36@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1036'],
            ['name' => 'usuario37', 'email' => 'usuario37@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1037'],
            ['name' => 'usuario38', 'email' => 'usuario38@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1038'],
            ['name' => 'usuario39', 'email' => 'usuario39@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1039'],
            ['name' => 'usuario40', 'email' => 'usuario40@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1040'],
            ['name' => 'usuario41', 'email' => 'usuario41@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1041'],
            ['name' => 'usuario42', 'email' => 'usuario42@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1042'],
            ['name' => 'usuario43', 'email' => 'usuario43@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1043'],
            ['name' => 'usuario44', 'email' => 'usuario44@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1044'],
            ['name' => 'usuario45', 'email' => 'usuario45@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1045'],
            ['name' => 'usuario46', 'email' => 'usuario46@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1046'],
            ['name' => 'usuario47', 'email' => 'usuario47@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1047'],
            ['name' => 'usuario48', 'email' => 'usuario48@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1048'],
            ['name' => 'usuario49', 'email' => 'usuario49@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1049'],
            ['name' => 'usuario50', 'email' => 'usuario50@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1050'],
            ['name' => 'usuario51', 'email' => 'usuario51@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1051'],
            ['name' => 'usuario52', 'email' => 'usuario52@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1052'],
            ['name' => 'usuario53', 'email' => 'usuario53@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1053'],
            ['name' => 'usuario54', 'email' => 'usuario54@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1054'],
            ['name' => 'usuario55', 'email' => 'usuario55@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1055'],
            ['name' => 'usuario56', 'email' => 'usuario56@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1056'],
            ['name' => 'usuario57', 'email' => 'usuario57@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1057'],
            ['name' => 'usuario58', 'email' => 'usuario58@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1058'],
            ['name' => 'usuario59', 'email' => 'usuario59@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1059'],
            ['name' => 'usuario60', 'email' => 'usuario60@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1060'],
            ['name' => 'usuario61', 'email' => 'usuario61@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1061'],
            ['name' => 'usuario62', 'email' => 'usuario62@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1062'],
            ['name' => 'usuario63', 'email' => 'usuario63@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1063'],
            ['name' => 'usuario64', 'email' => 'usuario64@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1064'],
            ['name' => 'usuario65', 'email' => 'usuario65@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1065'],
            ['name' => 'usuario66', 'email' => 'usuario66@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1066'],
            ['name' => 'usuario67', 'email' => 'usuario67@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1067'],
            ['name' => 'usuario68', 'email' => 'usuario68@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1068'],
            ['name' => 'usuario69', 'email' => 'usuario69@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1069'],
            ['name' => 'usuario70', 'email' => 'usuario70@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1070'],
            ['name' => 'usuario71', 'email' => 'usuario71@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1071'],
            ['name' => 'usuario72', 'email' => 'usuario72@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1072'],
            ['name' => 'usuario73', 'email' => 'usuario73@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1073'],
            ['name' => 'usuario74', 'email' => 'usuario74@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1074'],
            ['name' => 'usuario75', 'email' => 'usuario75@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1075'],
            ['name' => 'usuario76', 'email' => 'usuario76@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1076'],
            ['name' => 'usuario77', 'email' => 'usuario77@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1077'],
            ['name' => 'usuario78', 'email' => 'usuario78@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1078'],
            ['name' => 'usuario79', 'email' => 'usuario79@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1079'],
            ['name' => 'usuario80', 'email' => 'usuario80@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1080'],
            ['name' => 'usuario81', 'email' => 'usuario81@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1081'],
            ['name' => 'usuario82', 'email' => 'usuario82@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1082'],
            ['name' => 'usuario83', 'email' => 'usuario83@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1083'],
            ['name' => 'usuario84', 'email' => 'usuario84@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1084'],
            ['name' => 'usuario85', 'email' => 'usuario85@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1085'],
            ['name' => 'usuario86', 'email' => 'usuario86@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1086'],
            ['name' => 'usuario87', 'email' => 'usuario87@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1087'],
            ['name' => 'usuario88', 'email' => 'usuario88@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1088'],
            ['name' => 'usuario89', 'email' => 'usuario89@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1089'],
            ['name' => 'usuario90', 'email' => 'usuario90@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1090'],
            ['name' => 'usuario91', 'email' => 'usuario91@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1091'],
            ['name' => 'usuario92', 'email' => 'usuario92@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1092'],
            ['name' => 'usuario93', 'email' => 'usuario93@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1093'],
            ['name' => 'usuario94', 'email' => 'usuario94@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1094'],
            ['name' => 'usuario95', 'email' => 'usuario95@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1095'],
            ['name' => 'usuario96', 'email' => 'usuario96@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1096'],
            ['name' => 'usuario97', 'email' => 'usuario97@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1097'],
            ['name' => 'usuario98', 'email' => 'usuario98@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1098'],
            ['name' => 'usuario99', 'email' => 'usuario99@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1099'],
            ['name' => 'usuario100', 'email' => 'usuario100@sige.com', 'password' => 'Usuario@2026', 'perfil' => 'operador', 'pin' => '1100'],
        ];


        foreach ($usuarios as $u) {
            DB::table('users')->updateOrInsert(
                ['email' => $u['email']],
                [
                    'name' => $u['name'],
                    'password' => Hash::make($u['password']),
                    'perfil' => $u['perfil'],
                    'pin' => $u['pin'] ? Hash::make($u['pin']) : null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
